language: node_js
sudo: false
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm run coveralls
deploy:
  provider: npm
  email: "hello@andrewmmc.com"
  skip_cleanup: true
  api_key: $NPM_PUBLISH_TOKEN
  on:
    branch: master
    tags: true
